source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MyENS' do
  use_frameworks!

  # Pods for MyENS
  pod 'web3swift', '~> 1.1.5'

  target 'MyENSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyENSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
